spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/security_db
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: randomislerucun123@gmail.com
    password: ptpwfuvnswkkbrla
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    cookie-settings: # Settings applied to the refresh token cookie
      http-only: false    # Prevents JavaScript from reading the cookie (mitigates XSS) WARNING: must be true in Production
      secure: false       # Ensures the cookie is sent only over HTTPS; WARNING: must be true in Production
      maxAge: 2592000  # Lifetime in seconds (2592000s = 30 days)
      sameSite: Strict   # Restricts sending cookie on cross‑site requests (CSRF protection)
      path: /auth

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
